site:
  name: Tandemflug Lienz
  site: 'https://tandemflug-lienz.com'
  base: '/'
  trailingSlash: false
  googleSiteVerificationId: ''

metadata:
  title:
    default: Tandemflug Lienz
    template: '%s – Tandemflug Lienz'
  description: 'Tandemflug in Osttirol: Starte vom Zettersfeld oder Hochstein und gleite über das Drautal und die Lienzer Dolomiten.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Tandemflug Lienz
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    cardType: summary_large_image

i18n:
  language: de
  textDirection: ltr

apps:
  blog:
    isEnabled: false

analytics:
  vendors:
    googleAnalytics:
      id: null

ui:
  theme: 'system'
